MvcWebUI/Areas/Admin/Controllers/BranchController.cs
using DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.Services.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BranchController : Controller
    {
        private readonly IBranchService _branchService;

        public BranchController(IBranchService branchService)
        {
            _branchService = branchService;
        }
        public IActionResult Index()
        {
            return View(_branchService.GetAll());
        }
        public IActionResult AddBranch()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddBranch(Branch branch)
        {
            _branchService.Create(branch);
            return RedirectToAction("Index");
        }
        public IActionResult RemoveBranch(int id)
        {
            var result = _branchService.GetById(id);
            _branchService.Delete(result);
            return RedirectToAction("Index");
        }
        public IActionResult GetBranch(Branch branch)
        {
            var result = _branchService.GetById(branch.Id);
            return View(result);
        }
        public IActionResult UpdateBranch(int id)
        {
            var result = _branchService.GetById(id);
            return View(result);
        }

        [HttpPost]
        public IActionResult UpdateBranch(Branch branch)
        {
            _branchService.Update(branch);
            return RedirectToAction("Index");
        }

    }
}

MvcWebUI/Areas/Admin/Views/Branch/AddBranch.cshtml
@model Branch
@{
    ViewData["Title"] = "AddBranch";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div asp-validation-summary="All">

            </div>
            <form asp-action="AddBranch" method="post">
                <div class="form-group">
                    <label asp-for="Name">Şube İsmi</label>
                    <input name="Name" type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Address">Adres</label>
                    <input name="Address" type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber">Telefon Numarası</label>
                    <input name="PhoneNumber" type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Email">Email</label>
                    <input name="Email" type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Company">Şirket</label>
                    <input name="Company" type="text" class="form-control" />
                </div>

                <button type="submit" class="btn btn-primary">Kaydet</button>
            </form>
        </div>
    </div>
</div>

MvcWebUI/Areas/Admin/Views/Branch/Index.cshtml
@model List<Branch>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        @ViewData["Title"]

    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Branch Name</th>
                        <th>Address</th>
                        <th>PhoneNumber</th>
                        <th>Email</th>
                        <th>Company</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var branch in Model)
                    {
                    <tr>
                        <td>@branch.Id</td>
                        <td>@branch.Name</td>
                        <td>@branch.Address</td>
                        <td>@branch.PhoneNumber</td>
                        <td>@branch.Email</td>
                        <td>@branch.Company</td>
                        <td class="text-right">
                            
                            @Html.ActionLink("Güncelle", "UpdateBranch", "Branch", new { id = branch.Id }, new { @class = "btn btn-warning" })
                            @Html.ActionLink("Sil", "RemoveBranch", "Branch", new { id = branch.Id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

MvcWebUI/Areas/Admin/Views/Branch/UpdateBranch.cshtml
@model Branch
@{
    ViewData["Title"] = "UpdateBranch";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <form asp-action="UpdateBranch" method="post">
                <div class="form-group">
                    <label>Şube İsmi</label>
                    <input asp-for="Name" value="@Model.Name" type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Adres</label>
                    <input asp-for="Address" value="@Model.Address" type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Telefon Numarası</label>
                    <input asp-for="PhoneNumber" value="@Model.PhoneNumber" type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input asp-for="Email" value="@Model.Email" type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Şirket</label>
                    <input asp-for="Company" value="@Model.Company" type="text" class="form-control" />
                </div>

                <button type="submit" class="btn btn-primary">Düzenle</button>
            </form>
        </div>
    </div>
</div>